[theme]
primaryColor = "#e31b23"
backgroundColor = "#f5f6f8"
secondaryBackgroundColor = "#ffffff"
textColor = "#17191d"
font = "sans-serif"

[browser]
gatherUsageStats = false

[server]
headless = true
